### ISSUE TITLE
Could you add methods of class ImageAnalysis, like official descriptions?

### ISSUE THREAD

**Issue by BenoitKAO** [rockingbapidas/camerax-sample#1]
Thank you for your marvelous works!

Could you add methods of class ImageAnalysis, like descriptions in the official Docs?
https://developer.android.com/reference/kotlin/androidx/camera/core/ImageAnalysis

**Comment by rockingbapidas** [comment]
Ya, I am working on that.

**Comment by rockingbapidas** [comment]
with video capture, Image Analysis is not available yet. When it will stable I will implement that one also.
